name: Bulldozer
main: com.yahoo.tracebachi.Bulldozer
version: 6.2_Alpha
commands:
  box:
    description: Change the blocks in a box specified by the selection. 
    usage: §bIncorrect Command. For help, type /box
  cyl:
    description: Change the blocks in a cylinder specified by the selection.
    usage: §bIncorrect Command. For help, type /cyl
  sph:
    description: Change the blocks in a sphere specified by the selection.
    usage: §bIncorrect Command. For help, type /sph
  cone:
    description: Change the blocks in a cone specified by the selection.
    usage: §bIncorrect Command. For help, type /cone
  replace:
    description: Replace the blocks in the selection with the first ID to the second
    usage: §bIncorrect Command. For help, type /replace
  marker:
    description: Gives you the selection tool.
    usage: /marker
  clear:
    description: Clears your selection.
    usage: /clear
  clearall:
    description: Clears the selection for all players in the Server.
    usage: /clearall
  border:
    description: Make a border around the edges of the selection.
    usage: §bIncorrect Command. For help, type /border
  undo:
    description: Undo the last edit, all edits, or clears the undo storage
    usage: /undo [OR] /undo all [OR] /undo clear
  wipe:
    description: Remove the undo storage for all players.
    usage: /wipe