name: Bulldozer
main: com.yahoo.tracebachi.Bulldozer
version: 7_Alpha
commands:
  box:
    description: Change the blocks in a box specified by the selection. 
    usage: §bIncorrect Command. For help, type /box
  cyl:
    description: Change the blocks in a cylinder specified by the selection.
    usage: §bIncorrect Command. For help, type /cyl
  sph:
    description: Change the blocks in a sphere specified by the selection.
    usage: §bIncorrect Command. For help, type /sph
  cone:
    description: Change the blocks in a cone specified by the selection.
    usage: §bIncorrect Command. For help, type /cone
  replace:
    description: Replace the blocks in the selection with the first ID to the second
    usage: §bIncorrect Command. For help, type /replace
  copy:
    description: Copy the blocks in the selection.
    usage: §bIncorrect Command. For help, type /copy
  load:
    description: Load blocks from a file
    usage: §bIncorrect Command. For help, type /load
  kit:
    description: Gives you the selection tool and a pasting tool.
    usage: /kit
  clear:
    description: Clears your selection.
    usage: /clear
  clearall:
    description: Clears the selection for all players in the Server.
    usage: /clearall
  border:
    description: Make a border around the edges of the selection.
    usage: §bIncorrect Command. For help, type /border
  undo:
    description: Undo the last edit, all edits, or clears the undo storage
    usage: /undo [OR] /undo all [OR] /undo clear
  wipe:
    description: Remove the undo storage for all players.
    usage: /wipe